rivermap/urls.py
from django.urls import path
from . import views
from .views import RiverDetailView, RiverListView, \
    PrefectureListView, PrefectureDetailView, \
    SectionDetailView, SectionUpdateView, SectionListView, SpotUpdateView, SpotDetailView, SpotListView, \
    CommentUpdateView, CommentDeleteView

urlpatterns = [
    path('', views.rivermap, name="rivermap"),
    path('map/<slug:prefecture>/river/', RiverListView.as_view(), name='river-list'),
    path('map/<slug:prefecture>/section/', SectionListView.as_view(), name='section-list'),
    path('map/<slug:prefecture>/spot/', SpotListView.as_view(), name='spot-list'),
    path('map/river/', PrefectureListView.as_view(), name='prefecture-list'),
    path('map/<slug:prefecture>/river/<int:pk>/', RiverDetailView.as_view(), name='river-detail'),
    path('map/river/<int:pk>/', RiverDetailView.as_view(), name='river-detail'),
    path('map/<slug:prefecture>/section/<int:pk>/', SectionDetailView.as_view(), name='section-detail'),
    path('map/<slug:prefecture>/spot/<int:pk>/', SpotDetailView.as_view(), name='spot-detail'),
    path('map/<slug:slug>/', PrefectureDetailView.as_view(), name='prefecture-detail'),
    path('map/object/add/', views.add_object, name='add-object'),
    path('map/section/<int:pk>/update/', SectionUpdateView.as_view(), name='section-update'),
    path('map/spot/<int:pk>/update/', SpotUpdateView.as_view(), name='spot-update'),
    path('map/object/how-to-add/', views.how_to_add, name="how-to-add"),
    path('map/comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    path('map/comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
]

rivermap/models.py
import os

from PIL import Image
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Case, When, Value, IntegerField
from django.urls import reverse
from django.utils import timezone
from polymorphic.models import PolymorphicModel
from django.utils.translation import get_language

import rivermap
from blog.models import save_image

"""
Models:

Region
Prefecture
River
Observatory
Dam
MapObject
    Shop
    School
    RiverObject
        Section
        Spot
Comment
    CommentComment
    RiverComment
    ObservatoryComment
    MapObjectComment

"""


class Region(models.Model):
    name = models.CharField(max_length=255, unique=True)
    name_jp = models.CharField(max_length=255, unique=True)

    def __str__(self):
        if get_language() == "ja":
            return self.name_jp
        else:
            return self.name + " (" + self.name_jp + ")"


class Prefecture(models.Model):
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    name = models.CharField(max_length=255, unique=True)
    name_jp = models.CharField(max_length=255, unique=True)
    slug = models.SlugField()
    lat = models.FloatField(default=35.80251)
    lng = models.FloatField(default=139.19437)
    zoom = models.IntegerField(default=8)

    def __str__(self):
        if get_language() == "ja":
            return self.name_jp
        else:
            return self.name + " (" + self.name_jp + ")"

    def get_sections(self):
        return self.mapobject_set.instance_of(Section)

    def get_spots(self):
        return self.mapobject_set.instance_of(Spot)

    def get_absolute_url(self):
        return reverse('prefecture-detail', kwargs={'slug': self.slug})

    def section_count(self):
        return self.mapobject_set.instance_of(Section).count()

    def spot_count(self):
        return self.mapobject_set.instance_of(Spot).count()


class RiverSystem(models.Model):
    region = models.ManyToManyField(Region)
    prefecture = models.ManyToManyField(Prefecture)
    name = models.CharField(max_length=255)
    name_jp = models.CharField(max_length=255, unique=True)

    def __str__(self):
        if get_language() == "ja":
            return self.name_jp
        else:
            return self.name + " (" + self.name_jp + ")"

    def get_absolute_url(self):
        return reverse('river-detail', kwargs={'pk': self.pk})


class River(models.Model):
    region = models.ManyToManyField(Region)
    prefecture = models.ManyToManyField(Prefecture)
    riversystem = models.ManyToManyField(RiverSystem)
    name = models.CharField(max_length=255)
    name_jp = models.CharField(max_length=255, unique=True)

    def __str__(self):
        if get_language() == "ja":
            return self.name_jp
        else:
            return self.name + " (" + self.name_jp + ")"

    def get_absolute_url(self):
        return reverse('river-detail', kwargs={'pk': self.pk})

    def system_observatories_set(self):
        result = self.observatory_set.all().annotate(custom_order=Case(When(river=self, then=Value(1)), default=2,
                                    output_field=IntegerField(), )).order_by('custom_order', 'name')
        for riversystem in self.riversystem.all():
            result = result | riversystem.observatory_set.all()
        return result

    def system_dams_set(self):
        result = self.dam_set.all().annotate(custom_order=Case(When(river=self, then=Value(1)), default=2,
                                    output_field=IntegerField(), )).order_by('custom_order', 'name')
        for riversystem in self.riversystem.all():
            result = result | riversystem.dam_set.all()
        return result


class Observatory(models.Model):
    river = models.ForeignKey(River, on_delete=models.PROTECT)
    riversystem = models.ForeignKey(RiverSystem, on_delete=models.PROTECT, null=True)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    prefecture = models.ForeignKey(Prefecture, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    name_jp = models.CharField(max_length=255)
    url = models.CharField(max_length=2083, unique=True)
    level = models.FloatField(null=True, blank=True)
    date = models.DateTimeField(max_length=255, null=True, blank=True)

    def __str__(self):
        if get_language() == "ja":
            return self.name_jp
        else:
            return self.name + " (" + self.name_jp + ")"


class Dam(models.Model):
    river = models.ForeignKey(River, on_delete=models.PROTECT)
    riversystem = models.ForeignKey(RiverSystem, on_delete=models.PROTECT, null=True)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    prefecture = models.ForeignKey(Prefecture, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    name_jp = models.CharField(max_length=255)
    url = models.CharField(max_length=2083, unique=True)
    level = models.FloatField(null=True, blank=True)
    date = models.DateTimeField(max_length=255, null=True, blank=True)

    def __str__(self):
        if get_language() == "ja":
            return self.name_jp
        else:
            return self.name + " (" + self.name_jp + ")"


class MapObject(PolymorphicModel):
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    prefecture = models.ForeignKey(Prefecture, on_delete=models.PROTECT)
    name = models.CharField(max_length=255, default='')
    name_jp = models.CharField(max_length=255, default='')
    content = models.TextField(blank=True, null=True)
    date_added = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    lat = models.FloatField(
        validators=[MinValueValidator(21), MaxValueValidator(47)],
    )
    lng = models.FloatField(
        validators=[MinValueValidator(119), MaxValueValidator(151)],
    )

    def __str__(self):
        if get_language() == "ja":
            return self.name_jp
        else:
            return self.name + " (" + self.name_jp + ")"

    class Meta:
        ordering = ['name']

    def description(self):
        return self.__class__.__name__


class RiverObject(MapObject):
    river = models.ForeignKey(River, on_delete=models.PROTECT)
    observatory = models.ForeignKey(Observatory, on_delete=models.PROTECT, blank=True, null=True)
    dam = models.ForeignKey(Dam, on_delete=models.PROTECT, blank=True, null=True)
    high_water = models.FloatField(blank=True, null=True)
    middle_water = models.FloatField(blank=True, null=True)
    low_water = models.FloatField(blank=True, null=True)
    difficulty = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        abstract = True
        ordering = ['name']


class Shop(MapObject):

    def get_absolute_url(self):
        return reverse('shop-detail', kwargs={'pk': self.pk, 'prefecture': self.prefecture.slug})


class School(MapObject):

    def get_absolute_url(self):
        return reverse('school-detail', kwargs={'pk': self.pk, 'prefecture': self.prefecture.slug})


class Section(RiverObject):
    end_lat = models.FloatField(
        validators=[MinValueValidator(21), MaxValueValidator(47)],
    )
    end_lng = models.FloatField(
        validators=[MinValueValidator(119), MaxValueValidator(151)],
    )

    def get_absolute_url(self):
        return reverse('section-detail', kwargs={'pk': self.pk, 'prefecture': self.prefecture.slug})


class Spot(RiverObject):

    def get_absolute_url(self):
        return reverse('spot-detail', kwargs={'pk': self.pk, 'prefecture': self.prefecture.slug})


class Comment(PolymorphicModel):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image1 = models.ImageField(upload_to='comment_pics', null=True, blank=True)
    image2 = models.ImageField(upload_to='comment_pics', null=True, blank=True)
    image3 = models.ImageField(upload_to='comment_pics', null=True, blank=True)
    image4 = models.ImageField(upload_to='comment_pics', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['date_posted']

    def num_pics(self):
        num_pics = 0
        if self.image1:
            num_pics += 1
        if self.image2:
            num_pics += 1
        if self.image3:
            num_pics += 1
        if self.image4:
            num_pics += 1
        return num_pics

    def save(self, *args, **kwargs):
        if Comment.objects.filter(id=self.id):
            comment = Comment.objects.get(id=self.id)
            for [before, after] in [[comment.image1, self.image1], [comment.image2, self.image2], [comment.image3, self.image3], [comment.image4, self.image4]]:
                if before:
                    if not after or not before.url == after.url:
                        if os.path.isfile(before.path):
                            os.remove(before.path)
                            print(before.path)

        if not self.image3:
            self.image3 = self.image4
            self.image4 = None
        if not self.image2:
            self.image2 = self.image3
            self.image3 = self.image4
            self.image4 = None
        if not self.image1:
            self.image1 = self.image2
            self.image2 = self.image3
            self.image3 = self.image4
            self.image4 = None

        super(Comment, self).save(*args, **kwargs)
        if self.image1:
            save_image(Image.open(self.image1.path), self.image1.path)
        if self.image2:
            save_image(Image.open(self.image2.path), self.image2.path)
        if self.image3:
            save_image(Image.open(self.image3.path), self.image3.path)
        if self.image4:

rivermap/templates/rivermap/add_spot.html
{% extends "base_container.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% block style_sheets %}
    <link rel="stylesheet" href="{% static 'css/map-small.css' %}">
{% endblock style_sheets %}
{% block container_content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}

            <input type="hidden" value="{{ river.id }}" name="river">
            <input type="hidden" value="{{ prefecture.slug }}" name="prefecture">
            <fieldset class="form-group">
                <div class="border-bottom mb-4">
                    <legend>{% blocktrans with pref=prefecture %}New Spot in {{ pref }}{% endblocktrans %}</legend>
                    <h6>{{ prefecture.region }}</h6>
                </div>
                {% crispy form %}

            </fieldset>
        </form>
    </div>
{% endblock container_content %}

{% block scripts %}
<script src="{% static 'js/init-map-small.js' %}"></script>
<script>setCoords({{ prefecture.lat }}, {{ prefecture.lng }}, {{ prefecture.zoom }}); setType(1)</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4FzVGy5foAnrj5soy0wTrRF2Htq_ZZdI&language={{ LANGUAGE_CODE|default:"en-us" }}&callback=initMap"></script>
{% endblock scripts %}

rivermap/templates/rivermap/comment_form.html
{% extends "base_container.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block container_content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                {% if isUpdate %}
                <legend class="border-bottom mb-4">{% trans "Update Comment" %}</legend>
                {% else %}
                <legend class="border-bottom mb-4">{% trans "New Comment" %}</legend>
                {% endif %}
                {% crispy form %}
            </fieldset>
        </form>
    </div>
{% endblock container_content %}
{% block scripts %}
<script>
    function newCommentCancel(){
        window.location.href='{{ cancel_link }}'
    }
</script>
{% include 'show_next_image_script.html' %}
{% endblock scripts %}

rivermap/templates/rivermap/comment_with_picture.html
{% load i18n %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata row">
            <img class="rounded-circle article-img" src="{{ comment.author.profile.image.url }}">
            <div class="col">
                {% if not skip_parent %}
                <a href="{{ comment.parent.get_absolute_url }}">{{ comment.parent }}</a><br/>{% endif %}
                <a class="mr-2" href="{% url 'user-posts' comment.author.username %}">{{ comment.author }}</a>
                {% if LANGUAGE_CODE == "ja" %}
                    <small class="text-muted">{{ comment.date_posted|date:"Y年F d日" }}</small>
                {% else %}
                    <small class="text-muted">{{ comment.date_posted|date:"F d, Y" }}</small>
                {% endif %}
                {% if comment.author == user or user.is_staff%}
                    <div style="float: right;">
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'comment-update' comment.id %}">{% trans "Edit" %}</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'comment-delete' comment.id %}">{% trans "Delete" %}</a>
                    </div>
                {% endif %}
                <h2>{{ comment.title }}</h2>
            </div>
        </div>
        <p class="article-content">{{ comment.content }}</p>
        {% with post=comment %}
        {% include "four_images.html" %}
        {% endwith %}
    </div>
</article>

rivermap/templates/rivermap/comments_with_picture.html
{% load i18n %}
{% for comment in comments %}
    {% include "rivermap/comment_with_picture.html" %}
{% endfor %}

{% include "image_modal.html" %}

rivermap/templates/rivermap/comments_without_picture.html
{% load i18n %}
<h4 class="mb-3">{% trans "Comments" %}:</h4>
{% for comment in comments %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a href="{{ comment.parent.get_absolute_url }}">{{ comment.parent }}</a>
                <small class="text-muted">{% if LANGUAGE_CODE == "ja" %}{{ comment.date_posted|date:"Y年F d日" }}
                {% else %}{{ comment.date_posted|date:"F d, Y" }}{% endif %}</small>
            </div>
            {% if comment.author == user or user.is_staff%}
                <div style="float: right;">
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'comment-update' comment.id %}">{% trans "Edit" %}</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'comment-delete' comment.id %}">{% trans "Delete" %}</a>
                </div>
            {% endif %}
            <h2><a class="article-title" href="">{{ comment.title }}</a></h2>
            <p class="article-content">{{ comment.content }}</p>
        </div>
    </article>
{% endfor %}

rivermap/templates/rivermap/map.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% block style_sheets %}
    <link rel="stylesheet" href="{% static 'lib/css/chart-2.9.1.css' %}">
    <script src="{% static 'lib/js/fontawesome.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/map.css' %}">
{% endblock style_sheets %}
{% block content %}

<div class="window-container">
    <div class="header-break"></div>
    <div class="wrapper">
        <nav id="sidebar" style="height: 100%;">
            <div id="dismiss">
                <i class="fas fa-times fa-2x"></i>
            </div>
            <div class="sidebar-header">
                <h2 id="sb-river-name">{% trans "River Name" %}</h2>
                <h5 id="sb-section-name">{% trans "Section Name" %}</h5>
            </div>
            <div id="scroll-content">
                <div class="sidebar-content">
                    <p id="sb-content" class="content-section" style="padding: 5px;"></p>
                    <p id="sb-difficulty"></p>
                    <p id="sb-distance"></p>
                    <p id="sb-start"></p>
                    <p id="sb-end"></p>

                    <div class="tabs">
                        <div class="tab-button-outer">
                            <ul id="tab-button">
                                <li><a href="#tab01">{% trans "Water Level" %}</a></li>
                                <li><a href="#tab02">{% trans "Weather" %}</a></li>
                            </ul>
                        </div>
                        <div class="tab-select-outer">
                            <select id="tab-select">
                                <option value="#tab01"></option>
                                <option value="#tab02"></option>
                            </select>
                        </div>

                        <div id="tab01" class="tab-contents">
                            <h3>{% trans "Water Level" %}</h3>
                            <button id="sb-chart-168" class="btn btn-link nav-link" style="float: left;" onclick="loadChart(0, 'sb-chart', 168)">{% trans "1w" %}</button>
                            <button id="sb-chart-48" class="btn btn-link nav-link" style="float: left;" onclick="loadChart(0, 'sb-chart', 48)">{% trans "2d" %}</button>
                            <button id="sb-chart-24" class="btn btn-link nav-link" style="float: left;" onclick="loadChart(0, 'sb-chart', 24)">{% trans "1d" %}</button>
                            <button id="sb-chart-12" class="btn btn-link nav-link" onclick="loadChart(0, 'sb-chart', 12)">{% trans "12h" %}</button>
                            <div id="sb-chart-div">
                                <canvas id="sb-chart"></canvas>
                            </div>
                            <p id="sb-level"></p>
                            <p id="sb-observatory"></p>
                            <p id="sb-updated"></p>
                            <table class="table mb-0">
                                <tbody>
                                    <tr>
                                        <td id="sb-lw" class="lw-color" style="padding: 0;"></td>
                                        <td id="sb-mw" class="mw-color" style="padding: 0;"></td>
                                        <td id="sb-hw" class="hw-color" style="padding: 0;"></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div id="tab02" class="tab-contents">
                            <h2>{% trans "Weather" %}</h2>
                            <p>{% trans "To be done" %}</p>
                        </div>
                    </div>

                    <div class="content-section" style="margin: 0;">
                        {% if user.is_authenticated %}
                        <buton id="sb-new-comment" class="btn btn-primary btn-sm mt-1 mb-1" style="float: right;" onclick="newComment()">{% trans "Comment" %}</buton>
                        <h5 style="padding-top: 10px;">{% trans "Comments:" %}</h5>
                        <form method="POST" enctype="multipart/form-data" id="sb-comment-form" class="content-section" style="display: none;">
                            {% csrf_token %}
                            <input id="object_type" type="hidden" value="section" name="section">
                            <input id="id_section" type="hidden" value="123" name="section">
                            {% crispy form %}
                        </form>
                        {% else %}
                        <small style="float: right;"><a href="{% url 'login' %}">{%trans "Log in</a></br>to comment" %}</small>
                        <h5 style="padding-top: 10px;">{% trans "Comments:" %}</h5>
                        {% endif %}
                        <div id="sb-comments"></div>
                    </div>
                </div>

            </div>
        </nav>
        <div id="content" style="height: 100%; width: 100%;">
            <div class="row map-row">
                <div id="map" class="col-12"></div>
                <!--<div class="col-2">
                    <div class="content-section">
                        blabla
                        <div class="media">
                            blublu
                        </div>
                    </div>
                </div>-->
            </div>
        </div>
    </div>
</div>

<div id="riverinfo" style="margin: 0; padding: 5px;"></div>

{% include "image_modal.html" %}
{% endblock content %}
{% block scripts %}
{% include 'show_next_image_script.html' %}
<script src="{% static 'lib/js/chart-2.9.3.js' %}"></script>
<script src="{% static 'js/chart.js' %}"></script>
<script src="{% static 'js/comment.js' %}"></script>
<script src="{% static 'js/map.js' %}?v=1.5"></script>
<script src="{% static 'js/init-map.js' %}"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4FzVGy5foAnrj5soy0wTrRF2Htq_ZZdI&language={{ LANGUAGE_CODE|default:"en-us" }}&callback=initMap"></script>
{% endblock scripts %}

rivermap/templates/rivermap/prefecture_detail.html
{% extends "base_container.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block container_content %}
    <div class="content-section">
        <div class="media-head">
            <h3 class="article-title">{{ object }}</h3>
            <h5 class="article-title">{{ object.region }}</h5>
        </div>
        <div class="media content-section">
            <div class="media-body">
                <h5 class="text-muted">
                    <a href="{% url 'river-list' object.slug %}">{% trans "Rivers:" %} {{ object.river_set.count }}</a>
                </h5>
                <table class="table mb-0">
                    <tbody>
                        <tr>
                            <td class="py-1"><a href="#">{{ object.observatory_set.count }} {% trans "Observatories" %}</a></td>
                            <td class="py-1"><a href="#">{{ object.dam_set.count }} {% blocktrans count counter=object.dam_set.count %}Dam{% plural %}Dams{% endblocktrans %}</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="media content-section">
            <div class="media-body">
                <h5 class="text-muted">
                    <a href="{% url 'section-list' prefecture.slug %}">{% blocktrans count counter=object.section_count %}White Water Section{% plural %}White Water Sections{% endblocktrans %} ({{ object.section_count }}):</a>
                </h5>
                {% if object.section_count > 0 %}
                {% for section in object.get_sections %}
                    <small class="text-muted"><a href="{% url 'section-detail' object.pk section.id %}">{{ section }}</a></br></small>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="media content-section">
            <div class="media-body">
                <h5 class="text-muted">
                    <a href="{% url 'spot-list' prefecture.slug %}">{% blocktrans count counter=object.spot_count %}White Water Spot{% plural %}White Water Spots{% endblocktrans %} ({{ object.spot_count }}):</a>
                </h5>
                {% if object.spot_count > 0 %}
                {% for spot in object.get_spots %}
                    <small class="text-muted"><a href="{% url 'spot-detail' object.pk spot.id %}">{{ spot }}</a></br></small>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock container_content %}

rivermap/templates/rivermap/prefecture_list.html
{% extends "base_container.html" %}
{% load i18n %}
{% block container_content %}

<div class="row">
    <div class="col-12 col-sm-8 col-md-9">
        {% for region in regions %}
        <a class="anchor-point" id="{{ region.name }}"></a>
        <div class="content-section">
            <div class="media-head">
                <h3 class="article-title">{{ region }}</h3>
            </div>

        {% for prefecture in prefectures %}
            {% if prefecture.region == region %}
            <article class="media content-section">
                <div class="media-body">
                    <h6 class="mb-0"><a class="article-title" href="{% url 'prefecture-detail' prefecture.slug %}">{{ prefecture }}</a></h6>
                    <!--<small class="text-muted">
                        {{ prefecture.region }}
                    </small>-->
                    <small>
                        <table class="table mb-0">
                            <tbody>
                                <tr>
                                    <td class="py-1"><a href="{% url 'river-list' prefecture.slug %}">{{ prefecture.river_set.count }} {% blocktrans count counter=prefecture.river_set.count %}River{% plural %}Rivers{% endblocktrans %}</a></td>
                                    <td class="py-1"><a href="{% url 'section-list' prefecture.slug %}">{{ prefecture.section_count }} {% blocktrans count counter=prefecture.section_count %}Section{% plural %}Sections{% endblocktrans %}</a></td>
                                    <td class="py-1"><a href="{% url 'spot-list' prefecture.slug %}">{{ prefecture.spot_count }} {% blocktrans count counter=prefecture.spot_count %}Spot{% plural %}Spots{% endblocktrans %}</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </small>
                </div>
            </article>
            {% endif%}
        {% endfor %}
        </div>
        {% endfor %}
    </div>
    <div class="col-sm-4 col-md-3">
        <div class="content-section" style="position: fixed; z-index: 1;">
            {% for region in regions %}
            <p><a href="#{{ region.name }}">{{ region }}</a></p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock container_content %}

rivermap/templates/rivermap/river_list.html
{% extends "base_container.html" %}
{% load i18n %}
{% block container_content %}
    <div class="content-section">
        <div class="media-head">
            <h3 class="article-title">{{ prefecture }}</h3>
            <h5 class="article-title">{{ prefecture.region }}</h5>
        </div>

        {% include "pagination.html" %}
        {% for river in rivers %}
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <h5><a class="article-title" href="{% url 'river-detail' view.kwargs.prefecture river.id %}">{{ river }}</a></h5>
                    </div>
                    {% if river.section_set.count > 0 %}
                    <p class="article-content" style="margin: 0;">{{ river.section_set.count }} {% blocktrans count counter=river.section_set.count %}registered White Water Section{% plural %}registered White Water Sections{% endblocktrans %}</p>
                    {% endif %}{% if river.spot_set.count > 0 %}
                    <p class="article-content" style="margin: 0;">{{ river.spot_set.count }} {% blocktrans count counter=river.spot_set.count %}registered White Water Spot{% plural %}registered White Water Spots{% endblocktrans %}</p>
                    {% endif %}
                </div>
            </article>
        {% endfor %}

        {% include "pagination.html" %}

    </div>
{% endblock container_content %}

rivermap/templates/rivermap/user_map_objects.html
{% load i18n %}
<h4 class="mb-3">{% trans "Added Map Objects" %}:</h4>
<article class="content-section media-body">
    {% for map_object in map_objects %}
    <a class="article-title" href="{{ map_object.get_absolute_url }}">{% if LANGUAGE_CODE == "ja" %}{{ map_object.name_jp }}{% else %}{{ map_object.name }}{% endif %}</a>
    <small>(<a class="article-title" href="{% url 'river-detail' map_object.prefecture.slug map_object.river.pk %}">{% if LANGUAGE_CODE == "ja" %}{{ map_object.river.name_jp }}{% else %}{{ map_object.river.name }}{% endif %}</a>) -</small>
    <small><a class="article-title" href="{{ map_object.prefecture.get_absolute_url }}">{% if LANGUAGE_CODE == "ja" %}{{ map_object.prefecture.name_jp }}{% else %}{{ map_object.prefecture.name }}{% endif %}</a></small>
    <small class="text-muted">{% if LANGUAGE_CODE == "ja" %}{{ map_object.date_added|date:"Y年F d日" }}
    {% else %}{{ map_object.date_added|date:"F d, Y" }}{% endif %}</small>
    <br/>
    {% endfor %}
</article>